export const BOOKING_ERROR_CODES = {
  MAX_SEATS_EXCEEDED: 'MAX_SEATS_EXCEEDED',
  SEAT_ALREADY_BOOKED: 'SEAT_ALREADY_BOOKED',
  SEAT_ALREADY_HELD: 'SEAT_ALREADY_HELD',
  SEAT_ROOM_MISMATCH: 'SEAT_ROOM_MISMATCH',
  SHOWTIME_EXPIRED: 'SHOWTIME_EXPIRED',
  SEAT_LOCK_LOST: 'SEAT_LOCK_LOST',
  BOOKING_EXPIRED: 'BOOKING_EXPIRED',
  SEAT_NOT_HELD: 'SEAT_NOT_HELD',
};

export const MAX_SEATS_PER_BOOKING = 8;
