name: cineplex_client
description: CINEPLEX Client - Hệ thống Đặt Vé Rạp Chiếu Phim
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Networking & Storage
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  socket_io_client: ^3.0.2

  # Routing
  go_router: ^14.8.1

  # UI & Utilities
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  flutter_svg: ^2.1.0
  lucide_icons_flutter: ^3.1.20
  intl: ^0.20.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  image_picker: ^1.2.3
  camera: ^0.12.1

  # Shared Core & Theme & Models
  mobile_shared:
    path: ../mobile_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
