export enum ENotificationType {
  TICKET_CONFIRM = 'TICKET_CONFIRM',
  PROMOTION = 'PROMOTION',
  SHOWTIME_REMINDER = 'SHOWTIME_REMINDER',
  STOCK_ALERT = 'STOCK_ALERT',
  SYSTEM = 'SYSTEM',
  ACCOUNT = 'ACCOUNT',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

