export const ENV_VARS = {
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  CLOUDINARY_FOLDER: 'CLOUDINARY_FOLDER',
  MAIL_HOST: 'MAIL_HOST',
  MAIL_PORT: 'MAIL_PORT',
  MAIL_USER: 'MAIL_USER',
  MAIL_PASS: 'MAIL_PASS',
  MAIL_FROM: 'MAIL_FROM',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USER: 'DB_USER',
  DB_PASS: 'DB_PASS',
  DB_NAME: 'DB_NAME',
  ADMIN_MAIL: 'ADMIN_MAIL',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
  FRONTEND_URL: 'FRONTEND_URL',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_USER: 'REDIS_USER',
  REDIS_PASS: 'REDIS_PASS',
  REDIS_DB: 'REDIS_DB',

  // ngrok (sandbox callback tunnel)
  NGROK_URL: 'NGROK_URL',

  // MoMo Sandbox
  MOMO_PARTNER_CODE: 'MOMO_PARTNER_CODE',
  MOMO_ACCESS_KEY: 'MOMO_ACCESS_KEY',
  MOMO_SECRET_KEY: 'MOMO_SECRET_KEY',
  MOMO_ENDPOINT: 'MOMO_ENDPOINT',
  MOMO_REDIRECT_URL: 'MOMO_REDIRECT_URL',
  MOMO_IPN_URL: 'MOMO_IPN_URL',

  // VNPay Sandbox
  VNP_TMN_CODE: 'VNP_TMN_CODE',
  VNP_HASH_SECRET: 'VNP_HASH_SECRET',
  VNP_URL: 'VNP_URL',
  VNP_RETURN_URL: 'VNP_RETURN_URL',
  VNP_IPN_URL: 'VNP_IPN_URL',

  // PayPal Sandbox
  PAYPAL_CLIENT_ID: 'PAYPAL_CLIENT_ID',
  PAYPAL_CLIENT_SECRET: 'PAYPAL_CLIENT_SECRET',
  PAYPAL_ENVIRONMENT: 'PAYPAL_ENVIRONMENT',
  PAYPAL_RETURN_URL: 'PAYPAL_RETURN_URL',
  PAYPAL_CANCEL_URL: 'PAYPAL_CANCEL_URL',
  PAYPAL_WEBHOOK_ID: 'PAYPAL_WEBHOOK_ID',
};
